import { defineConfig } from "vitest/config";

/**
 * Vitest configuration for @platform/storage.
 *
 * Tests exercise:
 *   • The deterministic key generator (pure function — no I/O).
 *   • Asset manifest + upload-intent Zod schemas.
 *   • The in-memory adapter against the full MediaStore contract.
 *   • The R2 adapter with a stubbed @aws-sdk/client-s3 S3Client so we
 *     can assert on the SDK call shape without network egress.
 *
 * No real R2 traffic is ever generated by this suite — the CI build
 * has no R2 credentials and we want the suite green on contributors'
 * laptops.
 */
export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
    exclude: ["node_modules", "dist", ".turbo"],
    globals: false,
    testTimeout: 10_000,
    reporters: ["default"],
    typecheck: { enabled: false },
  },
});
