import type {
  AdHook,
  LocalizedString,
  ProductBenefit,
  ProductFaq,
  ProductImage,
  ProductReview,
  UniversalProduct,
} from "@platform/catalog-schema";
import type {
  BenefitsSection,
  CtaSection,
  DraftDocument,
  FaqSection,
  HeroSection,
  ImageGallerySection,
  Section,
  StickyCtaSection,
  TestimonialsSection,
} from "@platform/builder-schema";
import type { StoreConfig } from "@platform/stores";
import { deriveCatalogMetadataFromProduct } from "./catalog-metadata-defaults";

/**
 * Map a freshly assembled `UniversalProduct` (worker stage 12 output)
 * into a `DraftDocument` ready for `studio_draft.payload`.
 *
 * # Why this lives in apps/studio (not in @platform/builder-schema)
 *
 *   • The builder-schema package is intentionally agnostic of
 *     pipeline outputs — it describes the canvas, not the pipeline.
 *   • The worker package is intentionally agnostic of the builder
 *     shape — it produces a UniversalProduct + lets the publisher
 *     decide downstream format.
 *   • That leaves Studio as the only sensible owner: it's the layer
 *     that wires the pipeline's output INTO the builder's input.
 *
 * # Section policy
 *
 *   1. **Hero** — `headline` (with `title` fallback) + `subheadline`
 *      (with `description` fallback) + first image as media. Always
 *      emitted; the builder treats a draft without a hero as
 *      visually empty.
 *
 *   2. **Benefits** — emitted iff `product.benefits.length > 0`.
 *      Lucide icon name carried through from the pipeline. Column
 *      count picked from item count (3 by default; 2 if exactly 4
 *      items to keep the grid balanced).
 *
 *   3. **Image gallery** — emitted iff `product.images.length > 1`
 *      (first image already lives in the hero — no duplication).
 *
 *   4. **Testimonials** — emitted iff `product.reviews.length > 0`.
 *      Reviewer's name + city + rating + body. Uses Arabic name
 *      preferentially (matches the GCC-buyer audience).
 *
 *   5. **FAQ** — emitted iff `product.faq.length > 0`.
 *
 *   6. **CTA** — always emitted. Labels populated from the first ad
 *      hook (`product.hooks[0]`) when present, otherwise generic
 *      bilingual defaults. `primaryHref` defaults to `#order` so the
 *      Publish flow's URL rewrite can substitute the real path.
 *
 *   7. **Sticky CTA** — appended last when at least one ad hook
 *      exists, mirroring the conversion-first mobile pattern the
 *      Fanaa store uses (PLATFORM.md §11 stage 09).
 *
 * # Determinism
 *
 * Section ids are generated by the supplied `newId` callback so
 * tests can pin ids and diff payloads cleanly. The production
 * caller uses a small monotonically-incrementing helper that
 * matches the format used elsewhere in the Studio (see
 * `nextLocalId()` in drafts-service.ts).
 */
export function productToDraftDocument(
  product: UniversalProduct,
  opts: { slug: string; newId: () => string; storeConfig?: StoreConfig },
): DraftDocument {
  const { slug, newId } = opts;
  const sections: Section[] = [];

  sections.push(makeHero(product, newId));

  if (product.benefits.length > 0) {
    sections.push(makeBenefits(product.benefits, newId));
  }

  if (product.images.length > 1) {
    sections.push(makeGallery(product.images.slice(1), newId));
  }

  if (product.reviews.length > 0) {
    sections.push(makeTestimonials(product.reviews, newId));
  }

  if (product.faq.length > 0) {
    sections.push(makeFaq(product.faq, newId));
  }

  sections.push(makeCta(product, newId));

  if (product.hooks.length > 0) {
    sections.push(makeStickyCta(product.hooks[0], newId));
  }

  // Meta title MUST go through `pickLocale` too — a null in
  // `product.title.en` (which Claude does emit) would otherwise
  // bypass the cleanup in the sections and fail
  // `meta.title.en: Expected string, received null` at the root
  // DraftDocumentSchema parse, knocking out the WHOLE payload.
  //
  // Length-clamp BOTH meta locales before validation:
  //   • title:       z.string().max(200)
  //   • description: z.string().max(500)
  // Claude routinely emits descriptions well past 500 chars when
  // the strategy stage's `description` carries combined emotional +
  // functional copy; we clamp here so the payload validates and the
  // operator-edit experience starts from a complete-but-trimmed
  // baseline rather than an empty fallback.
  const heroSrc = safeStr(product.images[0]?.src);
  /*
   * M12 / Step 2 / Phase 2.3 — auto-derive the operator's catalog
   * panel defaults from the pipeline's UniversalProduct.
   *
   * `deriveCatalogMetadataFromProduct` is pure and deterministic
   * (see catalog-metadata-defaults.ts JSDoc). The operator can edit
   * any field in the Studio panel before publish; the publish flow
   * only upserts a catalog row when `priceMinor > 0`, which keeps
   * the legacy publish path (no catalog row) intact for drafts
   * created via "New draft" with no upstream pipeline output.
   *
   * Tier-A: NOT plumbing intake.offers through to here — the
   * UniversalProduct's `priceHint` already reflects the operator's
   * intake price, and the deterministic 1/2/3-pack ladder is the
   * same one the FanaaPublisher would have computed. Operators
   * adjust the ladder in the panel if the heuristic misses.
   */
  const catalogMetadata = deriveCatalogMetadataFromProduct({
    product,
    storeConfig: opts.storeConfig,
  });
  return {
    version: 1,
    meta: {
      title: clampLocale(pickLocale(product.title), 200),
      // `meta.slug` is the cosmetic SEO slug inside the payload —
      // distinct from the DB column `studio_draft.slug` which is
      // the lookup key. The DB slug is whatever the dispatcher
      // wrote (typically a runId verbatim, which contains
      // underscores). The payload's slug MUST match SLUG_PATTERN
      // (lowercase ASCII alphanumerics + hyphens). Normalise here
      // so the two can diverge without breaking lookups.
      slug: normaliseDraftSlug(slug),
      description: clampLocale(pickLocale(product.description), 500),
      // OG image comes from the hero image when present so the
      // publisher's social-card generator has something to render.
      ...(heroSrc ? { ogImage: heroSrc } : {}),
      keywords: [],
    },
    sections,
    catalogMetadata,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Section builders
// ─────────────────────────────────────────────────────────────────────────

function makeHero(product: UniversalProduct, newId: () => string): HeroSection {
  // Prefer headline (conversion-tuned) over title (catalog-tuned).
  // `pickLocale` carries through whichever locales are populated and
  // omits the missing ones — never emits `null` or empty strings that
  // would survive into the rendered UI as ugly placeholders.
  const headline = pickLocale(
    product.headline ?? product.title,
    product.title,
  );
  const subheadline = pickLocale(
    product.subheadline ?? product.description,
    product.description,
  );
  const heroImage = product.images[0];
  // Take the first ad hook's CTA as a label hint when available —
  // ad hooks are tuned for conversion language ("Shop now", "اطلبي").
  const ctaHint = product.hooks[0]?.cta;
  return {
    id: newId(),
    kind: "hero",
    enabled: true,
    title: headline,
    ...(hasAnyLocale(subheadline) ? { subtitle: subheadline } : {}),
    ...(ctaHint && hasAnyLocale(pickLocale(ctaHint))
      ? {
          ctaLabel: pickLocale(ctaHint),
          ctaHref: "#order",
        }
      : {}),
    media: buildHeroMedia(heroImage, product.title),
    align: "center",
  };
}

/**
 * Build a HeroSection-compatible MediaRef from a ProductImage.
 *
 * Returns `null` when the image is undefined OR has an empty/missing
 * `src` — MediaRefSchema requires `desktopSrc.min(1)` and one bad
 * MediaRef would invalidate the entire enclosing section.
 *
 * The `productTitle` fallback is wider than `LocalizedString` because
 * runtime LLM outputs occasionally substitute `null` for missing
 * locales (compile-time type says `string`; runtime says
 * `string | null | undefined`). Accepting the wider shape keeps the
 * call sites in `makeGallery` simple and matches what we actually
 * see in production.
 */
function buildHeroMedia(
  img: ProductImage | undefined,
  productTitle?: { ar?: string | null; en?: string | null },
): HeroSection["media"] {
  if (!img) return null;
  const src = safeStr(img.src);
  if (!src) return null;
  const alt =
    safeStr(img.alt?.en) ??
    safeStr(img.alt?.ar) ??
    safeStr(productTitle?.en) ??
    safeStr(productTitle?.ar);
  return {
    kind: "image",
    desktopSrc: src,
    ...(alt ? { alt } : {}),
    ...(img.width ? { width: img.width } : {}),
    ...(img.height ? { height: img.height } : {}),
  };
}

function makeBenefits(
  benefits: ProductBenefit[],
  newId: () => string,
): BenefitsSection {
  // 4 items → 2 columns for a balanced 2x2; otherwise 3 columns.
  const columns: 2 | 3 = benefits.length === 4 ? 2 : 3;
  return {
    id: newId(),
    kind: "benefits",
    enabled: true,
    items: benefits.slice(0, 12).map((b) => ({
      id: newId(),
      ...(safeStr(b.icon) ? { icon: safeStr(b.icon)! } : {}),
      title: pickLocale(b.title),
      ...(hasAnyLocale(pickLocale(b.body)) ? { body: pickLocale(b.body) } : {}),
    })),
    columns,
  };
}

function makeGallery(
  images: ProductImage[],
  newId: () => string,
): ImageGallerySection {
  // Filter out images with empty src — MediaRefSchema requires
  // `desktopSrc.min(1)` and one bad item would invalidate the
  // entire section under Zod's array validation.
  const items = images
    .slice(0, 24)
    .map((img) => buildHeroMedia(img))
    .filter((m): m is NonNullable<typeof m> => m !== null);
  return {
    id: newId(),
    kind: "image_gallery",
    enabled: true,
    items,
    columns: 3,
  };
}

function makeTestimonials(
  reviews: ProductReview[],
  newId: () => string,
): TestimonialsSection {
  return {
    id: newId(),
    kind: "testimonials",
    enabled: true,
    items: reviews.slice(0, 20).map((r) => {
      // TestimonialItemSchema caps: author 160, city 80. Real names
      // never approach these limits; the clamps are defensive against
      // a model that occasionally emits a full bio in the name field.
      const author = clamp(
        safeStr(r.name.ar) ?? safeStr(r.name.en) ?? "Verified buyer",
        160,
      );
      const cityRaw = safeStr(r.city.ar) ?? safeStr(r.city.en);
      const city = cityRaw ? clamp(cityRaw, 80) : undefined;
      return {
        id: newId(),
        author,
        ...(city ? { city } : {}),
        ...(typeof r.rating === "number" && r.rating >= 1 && r.rating <= 5
          ? { rating: r.rating }
          : {}),
        quote: pickLocale(r.body),
        avatar: null,
      };
    }),
    display: "grid",
  };
}

function makeFaq(faq: ProductFaq[], newId: () => string): FaqSection {
  return {
    id: newId(),
    kind: "faq",
    enabled: true,
    items: faq.slice(0, 30).map((item) => ({
      id: newId(),
      question: pickLocale(item.q),
      answer: pickLocale(item.a),
    })),
  };
}

function makeCta(product: UniversalProduct, newId: () => string): CtaSection {
  const hookCta = product.hooks[0]?.cta;
  const headline = pickLocale(
    product.headline ?? product.title,
    product.title,
  );
  // Fallback labels are intentionally non-empty in both locales so
  // the CtaSectionSchema (which requires `primaryLabel: LocalisedText`)
  // never emits an unhelpful blank button.
  const primaryLabel = hookCta
    ? pickLocale(hookCta, { ar: "اطلبي الآن", en: "Order now" })
    : { ar: "اطلبي الآن", en: "Order now" };
  return {
    id: newId(),
    kind: "cta",
    enabled: true,
    title: headline,
    primaryLabel,
    primaryHref: "#order",
    variant: "solid",
  };
}

function makeStickyCta(hook: AdHook, newId: () => string): StickyCtaSection {
  return {
    id: newId(),
    kind: "sticky_cta",
    enabled: true,
    label: pickLocale(hook.cta, { ar: "اطلبي الآن", en: "Order now" }),
    href: "#order",
    bottomOffsetPx: 0,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Locale-field helpers
// ─────────────────────────────────────────────────────────────────────────

/**
 * Coerce a value that the model might emit as null, undefined, or an
 * empty string into a strict `string | undefined`. The builder
 * schema's `LocalisedTextSchema` uses `z.string().optional()` which
 * accepts `string | undefined` and REJECTS `null` — Claude's structured
 * outputs occasionally substitute the latter for "no value" and that
 * single difference is enough to torpedo `DraftDocumentSchema.safeParse`.
 *
 * Returns `undefined` for any falsy input (null, undefined, ""), and
 * trims whitespace-only strings to undefined too — those render as
 * empty input boxes in the canvas, which is the same UX bug as an
 * outright missing value.
 */
function safeStr(v: unknown): string | undefined {
  if (typeof v !== "string") return undefined;
  const t = v.trim();
  return t.length > 0 ? t : undefined;
}

/**
 * Normalise a `LocalizedString` from a UniversalProduct stage output
 * into a shape that always passes `LocalisedTextSchema.safeParse`.
 *
 * Strategy:
 *   • Pass through populated `ar`/`en` from `primary`.
 *   • Fall back to `fallback` for any locale that's null/undefined/blank
 *     in `primary`.
 *   • Always returns a plain object — never throws — but the object
 *     may have both keys missing if neither source had content (then
 *     `hasAnyLocale` returns false and the caller usually omits the
 *     field entirely).
 *
 * Empty / null / whitespace-only strings are treated as "missing".
 * That's the right semantic for the canvas: a placeholder input is
 * better than a misleading empty-string-filled field.
 *
 * Compile-time type for `LocalizedString` is `Record<Locale, string>`
 * (strict), but runtime LLM outputs occasionally substitute `null`
 * for "no value". The looser parameter type below matches what we
 * actually see in production, while `safeStr` handles the
 * normalisation so callers don't have to.
 */
type LooseLocale =
  | LocalizedString
  | { ar?: string | null; en?: string | null }
  | undefined;

function pickLocale(
  primary: LooseLocale,
  fallback?: LooseLocale,
): { ar?: string; en?: string } {
  const out: { ar?: string; en?: string } = {};
  const ar = safeStr(primary?.ar) ?? safeStr(fallback?.ar);
  const en = safeStr(primary?.en) ?? safeStr(fallback?.en);
  if (ar) out.ar = ar;
  if (en) out.en = en;
  return out;
}

function hasAnyLocale(v: { ar?: string; en?: string }): boolean {
  return Boolean(v.ar || v.en);
}

/**
 * Truncate a string to at most `max` UTF-16 code units, appending a
 * Unicode ellipsis (U+2026) when truncation occurs.
 *
 * # Why ellipsis and why one char
 *
 * The trailing `…` gives the operator a visual signal that the field
 * was clamped and edit-time content was lost — important so they
 * don't accidentally publish a sentence that ends mid-clause without
 * knowing why. The ellipsis itself is exactly ONE UTF-16 code unit,
 * so we reserve one char from `max` for it and the final string is
 * guaranteed `<= max`. `z.string().max(N)` measures the same
 * underlying JS `.length`, so this matches Zod's semantics exactly.
 *
 * `trimEnd()` after slice handles the common case where the cut
 * point lands inside trailing whitespace from the source text.
 */
function clamp(str: string, max: number): string {
  if (str.length <= max) return str;
  return str.slice(0, max - 1).trimEnd() + "…";
}

/** Apply `clamp(value, max)` to every populated locale in a
 *  `{ar?, en?}` pair. Missing locales stay missing — clamp doesn't
 *  conjure a value where there wasn't one. */
function clampLocale(
  v: { ar?: string; en?: string },
  max: number,
): { ar?: string; en?: string } {
  const out: { ar?: string; en?: string } = {};
  if (v.ar) out.ar = clamp(v.ar, max);
  if (v.en) out.en = clamp(v.en, max);
  return out;
}

/**
 * Convert any string into a DraftSlugSchema-compliant slug.
 *
 * The builder schema's SLUG_PATTERN is strict:
 *
 *     /^[a-z0-9]([a-z0-9-]{0,78}[a-z0-9])?$/
 *
 * Production runIds use underscores (`run_mpiptq9l_pligqded`), which
 * the regex rejects. This normaliser:
 *
 *   1. Lowercases.
 *   2. Replaces every non-alphanumeric run with a single `-`.
 *      (Underscores, dots, Arabic glyphs, emoji — all flattened.)
 *   3. Collapses repeated hyphens.
 *   4. Strips leading/trailing hyphens (the first/last char must be
 *      alphanumeric per the pattern).
 *   5. Truncates to 80 chars.
 *   6. Falls back to `"draft"` if the result is empty (e.g. all-Arabic
 *      input that became `"-"` after step 2 and then nothing after
 *      step 4) — `DraftSlugSchema` requires `min(1)`.
 *
 * This is the SAME shape as `normaliseSlug` in drafts-service.ts —
 * duplicated rather than imported to avoid a cyclic dep
 * (drafts-service imports from product-to-draft would lift if we
 * shared the helper). The two MUST stay in sync.
 */
function normaliseDraftSlug(input: string): string {
  const cleaned = input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
  return cleaned || "draft";
}
