import type {
  AdHook,
  ProductBenefit,
  ProductFaq,
  ProductImage,
  ProductReview,
  UniversalProduct,
} from "@platform/catalog-schema";
import type {
  BenefitsSection,
  CtaSection,
  DraftDocument,
  FaqSection,
  HeroSection,
  ImageGallerySection,
  Section,
  StickyCtaSection,
  TestimonialsSection,
} from "@platform/builder-schema";

/**
 * Map a freshly assembled `UniversalProduct` (worker stage 12 output)
 * into a `DraftDocument` ready for `studio_draft.payload`.
 *
 * # Why this lives in apps/studio (not in @platform/builder-schema)
 *
 *   • The builder-schema package is intentionally agnostic of
 *     pipeline outputs — it describes the canvas, not the pipeline.
 *   • The worker package is intentionally agnostic of the builder
 *     shape — it produces a UniversalProduct + lets the publisher
 *     decide downstream format.
 *   • That leaves Studio as the only sensible owner: it's the layer
 *     that wires the pipeline's output INTO the builder's input.
 *
 * # Section policy
 *
 *   1. **Hero** — `headline` (with `title` fallback) + `subheadline`
 *      (with `description` fallback) + first image as media. Always
 *      emitted; the builder treats a draft without a hero as
 *      visually empty.
 *
 *   2. **Benefits** — emitted iff `product.benefits.length > 0`.
 *      Lucide icon name carried through from the pipeline. Column
 *      count picked from item count (3 by default; 2 if exactly 4
 *      items to keep the grid balanced).
 *
 *   3. **Image gallery** — emitted iff `product.images.length > 1`
 *      (first image already lives in the hero — no duplication).
 *
 *   4. **Testimonials** — emitted iff `product.reviews.length > 0`.
 *      Reviewer's name + city + rating + body. Uses Arabic name
 *      preferentially (matches the GCC-buyer audience).
 *
 *   5. **FAQ** — emitted iff `product.faq.length > 0`.
 *
 *   6. **CTA** — always emitted. Labels populated from the first ad
 *      hook (`product.hooks[0]`) when present, otherwise generic
 *      bilingual defaults. `primaryHref` defaults to `#order` so the
 *      Publish flow's URL rewrite can substitute the real path.
 *
 *   7. **Sticky CTA** — appended last when at least one ad hook
 *      exists, mirroring the conversion-first mobile pattern the
 *      Fanaa store uses (PLATFORM.md §11 stage 09).
 *
 * # Determinism
 *
 * Section ids are generated by the supplied `newId` callback so
 * tests can pin ids and diff payloads cleanly. The production
 * caller uses a small monotonically-incrementing helper that
 * matches the format used elsewhere in the Studio (see
 * `nextLocalId()` in drafts-service.ts).
 */
export function productToDraftDocument(
  product: UniversalProduct,
  opts: { slug: string; newId: () => string },
): DraftDocument {
  const { slug, newId } = opts;
  const sections: Section[] = [];

  sections.push(makeHero(product, newId));

  if (product.benefits.length > 0) {
    sections.push(makeBenefits(product.benefits, newId));
  }

  if (product.images.length > 1) {
    sections.push(makeGallery(product.images.slice(1), newId));
  }

  if (product.reviews.length > 0) {
    sections.push(makeTestimonials(product.reviews, newId));
  }

  if (product.faq.length > 0) {
    sections.push(makeFaq(product.faq, newId));
  }

  sections.push(makeCta(product, newId));

  if (product.hooks.length > 0) {
    sections.push(makeStickyCta(product.hooks[0], newId));
  }

  return {
    version: 1,
    meta: {
      title: {
        ar: product.title.ar,
        en: product.title.en,
      },
      slug,
      description: {
        ar: product.description.ar,
        en: product.description.en,
      },
      // OG image comes from the hero image when present so the
      // publisher's social-card generator has something to render.
      ...(product.images[0] ? { ogImage: product.images[0].src } : {}),
      keywords: [],
    },
    sections,
  };
}

// ─────────────────────────────────────────────────────────────────────────
// Section builders
// ─────────────────────────────────────────────────────────────────────────

function makeHero(product: UniversalProduct, newId: () => string): HeroSection {
  const headline = product.headline ?? product.title;
  const subheadline = product.subheadline ?? product.description;
  const heroImage = product.images[0];
  // Take the first ad hook's CTA as a label hint when available —
  // ad hooks are tuned for conversion language ("Shop now", "اطلبي").
  const ctaHint = product.hooks[0]?.cta;
  return {
    id: newId(),
    kind: "hero",
    enabled: true,
    title: { ar: headline.ar, en: headline.en },
    subtitle: { ar: subheadline.ar, en: subheadline.en },
    ...(ctaHint
      ? {
          ctaLabel: { ar: ctaHint.ar, en: ctaHint.en },
          ctaHref: "#order",
        }
      : {}),
    media: heroImage
      ? {
          kind: "image",
          desktopSrc: heroImage.src,
          alt:
            heroImage.alt.en ??
            heroImage.alt.ar ??
            product.title.en ??
            product.title.ar ??
            "",
          ...(heroImage.width ? { width: heroImage.width } : {}),
          ...(heroImage.height ? { height: heroImage.height } : {}),
        }
      : null,
    align: "center",
  };
}

function makeBenefits(
  benefits: ProductBenefit[],
  newId: () => string,
): BenefitsSection {
  // 4 items → 2 columns for a balanced 2x2; otherwise 3 columns.
  const columns: 2 | 3 = benefits.length === 4 ? 2 : 3;
  return {
    id: newId(),
    kind: "benefits",
    enabled: true,
    title: { ar: "", en: "" },
    items: benefits.slice(0, 12).map((b) => ({
      id: newId(),
      icon: b.icon,
      title: { ar: b.title.ar, en: b.title.en },
      body: { ar: b.body.ar, en: b.body.en },
    })),
    columns,
  };
}

function makeGallery(
  images: ProductImage[],
  newId: () => string,
): ImageGallerySection {
  return {
    id: newId(),
    kind: "image_gallery",
    enabled: true,
    title: { ar: "", en: "" },
    items: images.slice(0, 24).map((img) => ({
      kind: "image" as const,
      desktopSrc: img.src,
      alt: img.alt.en ?? img.alt.ar ?? "",
      ...(img.width ? { width: img.width } : {}),
      ...(img.height ? { height: img.height } : {}),
    })),
    columns: 3,
  };
}

function makeTestimonials(
  reviews: ProductReview[],
  newId: () => string,
): TestimonialsSection {
  return {
    id: newId(),
    kind: "testimonials",
    enabled: true,
    title: { ar: "", en: "" },
    items: reviews.slice(0, 20).map((r) => ({
      id: newId(),
      author: r.name.ar ?? r.name.en ?? "",
      ...(r.city.ar || r.city.en
        ? { city: r.city.ar ?? r.city.en ?? "" }
        : {}),
      rating: r.rating,
      quote: { ar: r.body.ar, en: r.body.en },
      avatar: null,
    })),
    display: "grid",
  };
}

function makeFaq(faq: ProductFaq[], newId: () => string): FaqSection {
  return {
    id: newId(),
    kind: "faq",
    enabled: true,
    title: { ar: "", en: "" },
    items: faq.slice(0, 30).map((item) => ({
      id: newId(),
      question: { ar: item.q.ar, en: item.q.en },
      answer: { ar: item.a.ar, en: item.a.en },
    })),
  };
}

function makeCta(product: UniversalProduct, newId: () => string): CtaSection {
  const hookCta = product.hooks[0]?.cta;
  const headline = product.headline ?? product.title;
  return {
    id: newId(),
    kind: "cta",
    enabled: true,
    title: { ar: headline.ar, en: headline.en },
    subtitle: { ar: "", en: "" },
    primaryLabel: hookCta
      ? { ar: hookCta.ar, en: hookCta.en }
      : { ar: "اطلبي الآن", en: "Order now" },
    primaryHref: "#order",
    variant: "solid",
  };
}

function makeStickyCta(hook: AdHook, newId: () => string): StickyCtaSection {
  return {
    id: newId(),
    kind: "sticky_cta",
    enabled: true,
    label: { ar: hook.cta.ar, en: hook.cta.en },
    href: "#order",
    bottomOffsetPx: 0,
  };
}
