import type { SectionKind } from "@platform/catalog-schema";
import type { AudienceTargeting } from "../prompts/audience-directive";

/**
 * Deterministic awareness/sophistication-aware section ordering (Step 4 §4.3,
 * ADR-S4-2).
 *
 * # Why this is deterministic, not an LLM call
 *
 * Section ORDER is a CRO *policy* decision, not a creative one. The creative
 * work (the actual copy + per-section content) is generated by the `copy` and
 * `section_content` stages. Ordering is governed by the Eugene Schwartz
 * awareness model + market sophistication — a well-understood direct-response
 * playbook. Encoding it as a pure function gives us:
 *
 *   • Reproducibility — the same intake always yields the same structure, which
 *     is the only way to *test* the success criterion ("different awareness ⇒
 *     different structure").
 *   • Zero hallucination — output is always a valid permutation of the store's
 *     section library; there is no "fall back to default because the model
 *     returned garbage" path.
 *   • Lower cost + latency — removes one LLM round-trip per draft (helps the
 *     per-draft cost ceiling).
 *
 * The mapping below is the single source of truth for "where does the page
 * start" per awareness stage, modulated by sophistication. The fanaa renderer
 * consumes the resulting `sectionOrder`; sections without grounded content
 * self-render to null, so this purely decides ORDER, never visibility.
 *
 * # Mobile-first lens
 *
 * On paid-social mobile traffic the first 1–2 viewports decide the sale, so
 * each awareness order front-loads the single most persuasive beat for that
 * reader: education for the unaware, differentiation for the solution-aware,
 * proof+offer for the most-aware.
 */

type Awareness = NonNullable<AudienceTargeting["awarenessLevel"]>;
type Sophistication = NonNullable<AudienceTargeting["sophisticationLevel"]>;

/**
 * Base story-section order per awareness stage (Schwartz). `hero` is pinned
 * first and `cross_sell`/`sticky_cta` are pinned last by `pinShellSections`,
 * so they are intentionally omitted here — these arrays describe the *story*
 * between the buy box and the related-products rail.
 */
const AWARENESS_ORDER: Record<Awareness, SectionKind[]> = {
  // Doesn't know they have the problem → educate first (mechanism + brand
  // story), earn the benefit claim, prove last.
  unaware: [
    "how_it_works",
    "founders_note",
    "benefits",
    "ingredients",
    "results_expectation",
    "lifestyle",
    "social_proof",
    "comparison",
    "guarantee",
    "faq",
  ],
  // Feels the pain, doesn't know solutions → benefit promise, then why it
  // works, then proof.
  "problem-aware": [
    "benefits",
    "how_it_works",
    "ingredients",
    "results_expectation",
    "social_proof",
    "lifestyle",
    "comparison",
    "founders_note",
    "guarantee",
    "faq",
  ],
  // Knows solutions exist, not this one → differentiate hard, early and often.
  "solution-aware": [
    "comparison",
    "how_it_works",
    "benefits",
    "ingredients",
    "social_proof",
    "results_expectation",
    "lifestyle",
    "founders_note",
    "guarantee",
    "faq",
  ],
  // Knows this product → lead with proof + risk reversal; close objections.
  "product-aware": [
    "social_proof",
    "results_expectation",
    "benefits",
    "guarantee",
    "ingredients",
    "comparison",
    "lifestyle",
    "how_it_works",
    "founders_note",
    "faq",
  ],
  // Ready to buy → proof + offer + reassurance, tight; minimal education.
  "most-aware": [
    "social_proof",
    "guarantee",
    "results_expectation",
    "benefits",
    "faq",
    "ingredients",
    "comparison",
    "lifestyle",
    "how_it_works",
    "founders_note",
  ],
};

/**
 * Sophistication deltas — added to a section's base position (negative = move
 * earlier). Sophistication doesn't change *where the reader starts* (that's
 * awareness) but *what evidence convinces them*: a fresh market accepts a plain
 * mechanism, while a jaded one needs differentiation, a unique mechanism, and
 * an identity/POV hook before generic benefit claims.
 */
const SOPHISTICATION_DELTA: Record<
  Sophistication,
  Partial<Record<SectionKind, number>>
> = {
  // Fresh market — explain the mechanism + what's inside up front.
  beginner: { how_it_works: -3, ingredients: -1 },
  // Standard — awareness order is already well-tuned.
  intermediate: {},
  // Skeptical — differentiation + unique mechanism + proof beat louder claims.
  advanced: { comparison: -3, how_it_works: -2, social_proof: -1, benefits: 1 },
  // Jaded experts — win on identity/POV + proof; demote generic benefit/hype.
  expert: {
    founders_note: -4,
    comparison: -2,
    social_proof: -1,
    benefits: 2,
  },
};

const HERO: SectionKind = "hero";
const TAIL_SHELL: SectionKind[] = ["cross_sell", "sticky_cta"];

export interface PlanInput {
  targeting?: AudienceTargeting;
  /** The store's supported section kinds (`templates.sectionLibrary`). */
  sectionLibrary: SectionKind[];
  /** The store default ordering, used when no awareness signal is present. */
  defaultOrdering: SectionKind[];
}

export interface PlanResult {
  sections: SectionKind[];
  /** "default" when no awareness signal drove the plan; "awareness" otherwise. */
  basis: "default" | "awareness";
  /** Human-readable explanation, surfaced in StructureOutput.rationale + logs. */
  rationale: string;
}

/**
 * Pin the commerce-shell sections: `hero` first, then `cross_sell` →
 * `sticky_cta` last (only those present in the library). The fanaa renderer
 * ignores these (they live in the commerce shell), but other publishers + the
 * Studio preview honour them, so we keep the contract correct.
 */
function pinShellSections(
  order: SectionKind[],
  library: ReadonlySet<SectionKind>,
): SectionKind[] {
  const body = order.filter(
    (s) => s !== HERO && !TAIL_SHELL.includes(s),
  );
  const result: SectionKind[] = [];
  if (library.has(HERO)) result.push(HERO);
  result.push(...body);
  for (const tail of TAIL_SHELL) if (library.has(tail)) result.push(tail);
  return result;
}

export function planSectionOrder(input: PlanInput): PlanResult {
  const library = new Set(input.sectionLibrary);
  const awareness = input.targeting?.awarenessLevel as Awareness | undefined;
  const sophistication = input.targeting?.sophisticationLevel as
    | Sophistication
    | undefined;

  // No awareness signal → preserve the store's curated default exactly.
  if (!awareness || !AWARENESS_ORDER[awareness]) {
    return {
      sections: input.defaultOrdering,
      basis: "default",
      rationale: "no_awareness_signal_store_default",
    };
  }

  const base = AWARENESS_ORDER[awareness];
  const deltas =
    (sophistication && SOPHISTICATION_DELTA[sophistication]) || {};

  // Weight each base section by (position + sophistication delta), keeping the
  // original index as a stable tie-breaker.
  const weighted = base
    .filter((s) => library.has(s))
    .map((s, i) => ({ s, i, w: i + (deltas[s] ?? 0) }));
  weighted.sort((a, b) => a.w - b.w || a.i - b.i);
  const ordered = weighted.map((x) => x.s);

  // Append any library sections the playbook doesn't explicitly place
  // (e.g. creative_strip, specifications) in library order, so we never drop a
  // store-supported kind.
  for (const s of input.sectionLibrary) {
    if (!ordered.includes(s) && !TAIL_SHELL.includes(s) && s !== HERO) {
      ordered.push(s);
    }
  }

  const sections = pinShellSections(ordered, library);
  return {
    sections,
    basis: "awareness",
    rationale: `awareness=${awareness}; sophistication=${sophistication ?? "n/a"}`,
  };
}
